services:
  db:
    image: postgres:13
    container_name: school_db
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: school_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - school_network

volumes:
  postgres_data:

networks:
  school_network:
    driver: bridge
