"""Add GroupStudents

Revision ID: 13f1f0f67ca6
Revises: 9474168def7e
Create Date: 2025-01-24 23:29:48.589584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f1f0f67ca6'
down_revision: Union[str, None] = '9474168def7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_group',
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_group'], ['s_group.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id_group', 'id_student')
    )
    op.drop_constraint('lesson_student_id_fkey', 'lesson', type_='foreignkey')
    op.drop_column('lesson', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('lesson_student_id_fkey', 'lesson', 'student', ['student_id'], ['id'])
    op.drop_table('student_group')
    # ### end Alembic commands ###
