"""да пиздец

Revision ID: 2e9552d517cd
Revises: 770a4412d110
Create Date: 2025-01-25 01:09:11.482247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9552d517cd'
down_revision: Union[str, None] = '770a4412d110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_group',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['s_group.id'], name='student_group_group_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='student_group_student_id_fkey')
    )
    # ### end Alembic commands ###
