"""молимся всей бригадой

Revision ID: 3461c46f2772
Revises: 093dea7da0ce
Create Date: 2025-01-25 00:42:40.069899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3461c46f2772'
down_revision: Union[str, None] = '093dea7da0ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_student')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_student',
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name='lesson_student_lesson_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='lesson_student_student_id_fkey'),
    sa.PrimaryKeyConstraint('lesson_id', 'student_id', name='lesson_student_pkey')
    )
    # ### end Alembic commands ###
