"""Add foreign key from Lesson to Student

Revision ID: 6cb8cfe27059
Revises: 85f4707639f2
Create Date: 2025-01-24 22:56:23.247875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb8cfe27059'
down_revision: Union[str, None] = '85f4707639f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lesson', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lesson', type_='foreignkey')
    op.drop_column('lesson', 'student_id')
    # ### end Alembic commands ###
