"""да пиздец

Revision ID: 770a4412d110
Revises: 693694b75413
Create Date: 2025-01-25 00:58:58.619367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770a4412d110'
down_revision: Union[str, None] = '693694b75413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'id_group',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'id_group',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
