"""я даун

Revision ID: 7f65c47551d3
Revises: 7a590f4bd6a8
Create Date: 2025-01-24 23:41:32.677803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f65c47551d3'
down_revision: Union[str, None] = '7a590f4bd6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'student', 's_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'group_id')
    # ### end Alembic commands ###
