"""я даун, ебись оно все конем, когда-нибудь я буду продумывать заранене

Revision ID: c582865faf7f
Revises: 7f65c47551d3
Create Date: 2025-01-24 23:49:21.034803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c582865faf7f'
down_revision: Union[str, None] = '7f65c47551d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
