"""молимся всей бригадой

Revision ID: d08b6e701a63
Revises: c582865faf7f
Create Date: 2025-01-24 23:52:25.119860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08b6e701a63'
down_revision: Union[str, None] = 'c582865faf7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_student',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'student_id')
    )
    op.drop_constraint('student_group_id_fkey', 'student', type_='foreignkey')
    op.drop_column('student', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('student_group_id_fkey', 'student', 's_group', ['group_id'], ['id'])
    op.drop_table('lesson_student')
    # ### end Alembic commands ###
